### ISSUE TITLE
Closes when using l

### ISSUE THREAD

**Issue by jeepwk2** [anilshanbhag/RobinhoodShell#1]
When I use "l," the program returns errors after listing my portfolio value and closes the application.

**Comment by anilshanbhag** [comment]
Could you post the error you see ? 
Also, feel free to submit a pull request if you fix the issue. It is probably a minor issue as your said your portfolio is being listed.

**Comment by ShaunHoyes** [comment]
I see the same error with the `l` command; here is the error message:
```
Traceback (most recent call last):
  File "./RobinhoodShell/shell.py", line 183, in <module>
    RobinhoodShell().cmdloop()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "./RobinhoodShell/shell.py", line 56, in do_l
    raw_data = self.trader.quotes_data(symbols)
  File "/Users/home/RobinhoodShell/Robinhood.py", line 228, in quotes_data
    raise NameError('Invalid Symbols: ' + ",".join(stocks)) #TODO: custom exception
NameError: Invalid Symbols: 
```

**Comment by anilshanbhag** [comment]
The issue should be fixed now. Re-open if you still get an error.
