### ISSUE TITLE
can't get quotes for Goog

### ISSUE THREAD

**Issue by markmark1** [anilshanbhag/RobinhoodShell#28]
yes same here  pls fix

 q goog
Traceback (most recent call last):
  File "./shell.py", line 613, in <module>
    RobinhoodShell().cmdloop()
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/cmd.py", line 217, in onecmd
    return func(arg)
  File "./shell.py", line 481, in do_q
    raw_data = self.trader.get_stock_marketdata(instruments)
  File "/Users/sk/RobinhoodShell/Robinhood/Robinhood.py", line 465, in get_stock_marketdata
    return info['results']
KeyError: 'results'
(RobinhoodShell) mark@marks-Air RobinhoodShell (master)*$ ./shell.py 
Welcome to the Robinhood shell. Type help or ? to list commands.

**Comment by anilshanbhag** [comment]
```
> q GOOG
┌Quote List──────────────┬─────────┬───────────────────────────┬───────────────┬───────────────┐
│ Symbol │ Current Price │   Open  │           Change          │      Ask      │ Bid           │
├────────┼───────────────┼─────────┼───────────────────────────┼───────────────┼───────────────┤
│  GOOG  │    1238.55    │ 1229.93 │ 8.61999999999989 (00.70%) │ 1237.37 x 300 │ 1236.37 x 100 │
└────────┴───────────────┴─────────┴───────────────────────────┴───────────────┴───────────────┘
```

Works fine for me.

**Comment by markmark1** [comment]
No doesn’t got the error   
  

  
  

  
  
>

**Comment by markmark1** [comment]
How to sell options ?
  

  
  

  
  
>
