### ISSUE TITLE
error when listing watchlist

### ISSUE THREAD

**Issue by johncallen1** [anilshanbhag/RobinhoodShell#5]
I get the following error when using the W and L command.

> w
Traceback (most recent call last):
  File "./shell.py", line 300, in <module>
    RobinhoodShell().cmdloop()
  File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "./shell.py", line 99, in do_w
    table.column_headers = ["symbol", "current price"]
  File "/usr/local/lib/python2.7/dist-packages/beautifultable/beautifultable.py", line 167, in __setattr__
    super(BeautifulTable, self).__setattr__(name, value)
  File "/usr/local/lib/python2.7/dist-packages/beautifultable/beautifultable.py", line 299, in column_headers
    header = self._validate_row(value)
  File "/usr/local/lib/python2.7/dist-packages/beautifultable/beautifultable.py", line 378, in _validate_row
    self._initialize_table(len(row))
  File "/usr/local/lib/python2.7/dist-packages/beautifultable/beautifultable.py", line 364, in _initialize_table
    self._column_alignments = AlignmentMetaData(self, [self.default_alignment] * column_count)
  File "/usr/local/lib/python2.7/dist-packages/beautifultable/meta.py", line 8, in __init__
    self.validate(i)
  File "/usr/local/lib/python2.7/dist-packages/beautifultable/meta.py", line 24, in validate
    + ', was {}'.format(value))
TypeError: 'type' object is not iterable

**Comment by anilshanbhag** [comment]
I am unable to reproduce it, do you have any items on your watchlist in Robinhood ? What are they ?
